### PR TITLE
Revert "add temporary run_constrained for autopep8"

### PR DESCRIPTION
**Pull request by izahn**
This reverts commit 7f953f72cc0db32d9f7eecf8a6983abef24cfff3.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by izahn** [comment]
@conda-forge-admin please rerender

**Comment by izahn** [comment]
@conda-forge/jupyter-lsp I think this is safe now.

**Comment by bollwyvl** [comment]
Thanks for the contribution, but the tests over here are rather lightweight so "green is good" isn't probably good enough over here. Perhaps you could PR this over [on the upstream](https://github.com/jupyter-lsp/jupyterlab-lsp/blob/8d904f9913b676838d6e4fcd6448b2b4b597d7ef/requirements/github-actions.yml#L15) before relaxing the pin here.... we wouldn't even have wait to get it merged, necessarily, as the upstream never actually _ships_ that pin, even behind an `[extra]` flag...

**Comment by bollwyvl** [comment]
Actually: looking at the pin in question: this is ignoring out a specific _build_ (`1.6.0=*_0`) and that build is _still and always will be broken_... but either way, we can evaluate getting rid of it once upstream is changed. Given this has happened a _number_ of times, it might be worth keeping the pin in, just so we have a record of, "yeah, auotpep8 can break stuff." I'd be a lot happier if that feedstock was running tests, but not looking for more work.

**Comment by izahn** [comment]
Ah right, I see. I was trying to solve this problem:
```
$ mamba install -q jupyter-lsp-python=1.5.1 spyder=5.2.1
Encountered problems while solving:
  - package python-lsp-server-1.3.3-pyhd8ed1ab_0 requires autopep8 >=1.6.0,<1.7.0, but none of the providers can be installed
```
and when I saw the package pin I hoped the fix would be as easy as removing it, but I see now this won't work until `autopep8 1.6.1`. Sorry for the noise.

**Comment by krassowski** [comment]
I wonder why it does not install 1.6.0_1 though? Did you try solving with `conda`? While I do find `mamba` better in most cases, maybe it does not support build pins properly?

**Comment by izahn** [comment]
Hmm the plot thickens...

```
$ mamba create -q -n test autopep8=1.6 'jupyter-lsp-python>=1.5.1' 'spyder=5.2.1=py39hf3d152e_1'                                                                  (base) 
Encountered problems while solving:
  - package jupyter-lsp-python-1.5.1-pyhd8ed1ab_0 has constraint autopep8 !=1.6.0 *_0 conflicting with autopep8-1.6.0-pyhd8ed1ab_0
```
Even when being 100% explicit `mamba` isn't buying it:
```
$ mamba create -q -n test 'autopep8=1.6.0=pyhd8ed1ab_1' 'jupyter-lsp-python>=1.5.1' 'spyder=5.2.1=py39hf3d152e_1'                                            (base) 
Encountered problems while solving:
  - package jupyter-lsp-python-1.5.1-pyhd8ed1ab_0 has constraint autopep8 !=1.6.0 *_0 conflicting with autopep8-1.6.0-pyhd8ed1ab_1
```
which seems to suggest that indeed `mamba` isn't reading that pin right. But then `conda` doesn't do any better:
```
$ conda create -q -n test 'autopep8=1.6.0=pyhd8ed1ab_1' 'jupyter-lsp-python>=1.5.1' 'spyder=5.2.1=py39hf3d152e_1'                                                 (base) 
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package toml conflicts for:
spyder==5.2.1=py39hf3d152e_1 -> pylint[version='>=2.5.0'] -> toml[version='>=0.7.1|>=0.9.2']
autopep8==1.6.0=pyhd8ed1ab_1 -> toml

Package entrypoints conflicts for:
jupyter-lsp-python[version='>=1.5.1'] -> jupyter-lsp==1.5.1=pyhd8ed1ab_0 -> entrypoints
spyder==5.2.1=py39hf3d152e_1 -> keyring[version='>=17.0.0'] -> entrypoints[version='>=0.2.2']

Package autopep8 conflicts for:
spyder==5.2.1=py39hf3d152e_1 -> python-lsp-server[version='>=1.3.2,<1.4.0'] -> autopep8[version='>=1.6.0,<1.7.0']
jupyter-lsp-python[version='>=1.5.1'] -> python-lsp-server[version='>=1'] -> autopep8[version='<1.6.0|>=1.6.0,<1.7.0']
```
So maybe there is a problem with the why the pin is specified here?

**Pull request closed without merging**
